baseURL: "https://incomparable-kashata-baf662.netlify.app/"
languageCode: en-us
title: aainfo
theme: PaperMod
enableRobotsTXT: true
params:
  defaultTheme:  dark #auto,light
  disableThemeToggle: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideSummary: false
  imageUrl: "/img/zwsem.jpeg"
    imageWidth: 60
    imageHeight: 120

assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/img/zwsem.jpeg"

label:
    text: "Home"
    icon: /img/zwsem.jpeg
    iconHeight: 35

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
  main:
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 40
  
      